"""Tests for core.key_loader with real keys generated by ``cryptography`` (SPEC §7.8, §10.2)."""

from __future__ import annotations

from pathlib import Path

import pytest
from cryptography.hazmat.primitives import serialization as ser
from cryptography.hazmat.primitives.asymmetric import dsa, ec, ed25519, rsa

from pyssh import strings
from pyssh.core.key_loader import KeyLoadError, PassphraseRequired, load_private_key

PASS = "rahasia kunci é"


def _write(path: Path, key, fmt, passphrase: str | None = None) -> Path:
    enc = ser.BestAvailableEncryption(passphrase.encode()) if passphrase else ser.NoEncryption()
    path.write_bytes(key.private_bytes(ser.Encoding.PEM, fmt, enc))
    return path


@pytest.fixture
def keys(tmp_path: Path) -> dict[str, Path]:
    openssh, pem, pkcs8 = (
        ser.PrivateFormat.OpenSSH,
        ser.PrivateFormat.TraditionalOpenSSL,
        ser.PrivateFormat.PKCS8,
    )
    return {
        "ed25519": _write(tmp_path / "ed", ed25519.Ed25519PrivateKey.generate(), openssh),
        "ed25519_pass": _write(
            tmp_path / "ed_pass", ed25519.Ed25519PrivateKey.generate(), openssh, PASS
        ),
        "rsa_pem": _write(tmp_path / "rsa", rsa.generate_private_key(65537, 2048), pem),
        "rsa_pem_pass": _write(
            tmp_path / "rsa_pass", rsa.generate_private_key(65537, 2048), pem, PASS
        ),
        "ecdsa": _write(tmp_path / "ec", ec.generate_private_key(ec.SECP256R1()), openssh),
        "ecdsa_pem_pass": _write(
            tmp_path / "ec_pass", ec.generate_private_key(ec.SECP384R1()), pem, PASS
        ),
        "rsa_pkcs8": _write(tmp_path / "pk8", rsa.generate_private_key(65537, 2048), pkcs8),
        "dsa": _write(tmp_path / "dsa", dsa.generate_private_key(1024), pem),
    }


@pytest.mark.parametrize(
    ("name", "key_type"),
    [
        ("ed25519", "ssh-ed25519"),
        ("rsa_pem", "ssh-rsa"),
        ("ecdsa", "ecdsa-sha2-nistp256"),
    ],
)
def test_load_without_passphrase(keys, name: str, key_type: str) -> None:
    assert load_private_key(str(keys[name])).get_name() == key_type


@pytest.mark.parametrize(
    ("name", "key_type"),
    [
        ("ed25519_pass", "ssh-ed25519"),
        ("rsa_pem_pass", "ssh-rsa"),
        ("ecdsa_pem_pass", "ecdsa-sha2-nistp384"),
    ],
)
def test_encrypted_keys(keys, name: str, key_type: str) -> None:
    with pytest.raises(PassphraseRequired):
        load_private_key(str(keys[name]))
    with pytest.raises(PassphraseRequired):
        load_private_key(str(keys[name]), "")  # empty passphrase counts as none
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(keys[name]), "wrong passphrase")
    assert info.value.code == "KEY_BAD_PASSPHRASE"
    assert info.value.message == strings.KEY_BAD_PASSPHRASE
    assert load_private_key(str(keys[name]), PASS).get_name() == key_type


def test_passphrase_for_unencrypted_key_is_ignored(keys) -> None:
    assert load_private_key(str(keys["ed25519"]), "unused").get_name() == "ssh-ed25519"


def test_putty_key(tmp_path: Path) -> None:
    ppk = tmp_path / "key.ppk"
    ppk.write_text("PuTTY-User-Key-File-3: ssh-ed25519\nEncryption: none\n")
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(ppk))
    assert info.value.code == "KEY_PPK_UNSUPPORTED"
    assert "PuTTYgen" in info.value.message and "puttygen" in info.value.message


def test_missing_file(tmp_path: Path) -> None:
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(tmp_path / "nope"))
    assert info.value.code == "KEY_NOT_FOUND"
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(tmp_path))  # a directory is not a key file
    assert info.value.code == "KEY_NOT_FOUND"


def test_garbage(tmp_path: Path) -> None:
    junk = tmp_path / "junk"
    junk.write_text("hello world\n")
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(junk))
    assert info.value.code == "KEY_INVALID"
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(junk), "some passphrase")
    assert info.value.code == "KEY_BAD_PASSPHRASE"  # SPEC §7.8 rule 6


def test_pkcs8_is_reported_as_invalid_with_conversion_hint(keys) -> None:
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(keys["rsa_pkcs8"]))
    assert info.value.code == "KEY_INVALID"
    assert "ssh-keygen -p -f" in info.value.message


def test_unsupported_key_type(keys) -> None:
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(keys["dsa"]))
    assert info.value.code == "KEY_UNSUPPORTED_TYPE"


def test_tilde_is_expanded(keys, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    home = tmp_path / "home"
    (home / ".ssh").mkdir(parents=True)
    (home / ".ssh" / "id_ed25519").write_bytes(keys["ed25519"].read_bytes())
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("USERPROFILE", str(home))
    assert load_private_key("~/.ssh/id_ed25519").get_name() == "ssh-ed25519"


def test_unreadable_file(keys, monkeypatch: pytest.MonkeyPatch) -> None:
    def deny(self, *args, **kwargs):
        raise PermissionError("denied")

    monkeypatch.setattr(Path, "open", deny)
    with pytest.raises(KeyLoadError) as info:
        load_private_key(str(keys["ed25519"]))
    assert info.value.code == "KEY_INVALID"
